kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aac-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "ocs-storagecluster-cephfs"
  volumeMode: Block
